apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - name: ping
        image: us-central1-docker.pkg.dev/boris001/containers/ping:002
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2Gi"  # Maximum memory allowed
            cpu: "0.5"       
          requests:
            memory: "2Gi"  # Initial memory request
            cpu: "0.5"       # Initial CPU request
---
apiVersion: v1
kind: Service
metadata:
  name: ping
  namespace: dev
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: ping
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 8080